### ISSUE TITLE
Enhancement - ability to lock triangles in Push and PSplt

### ISSUE THREAD

**Issue by DaveBenham** [dbgrande/GrandeModular#10]
Presumably the Push module is designed to be used during performance, but it is very easy to accidently press one of the triangles when intending to press a button. A context menu to lock the triangle state would be most welcome.

To a lesser extent, it would also be nice to have on PSplt, but not really critical.

Thanks

**Comment by dbgrande** [comment]
Actually, it was designed for debug—I've never done, and probably never will do a performance using VCV Rack.

However, this issue makes sense.  A possibility is to require that the triangle buttons need to be held for two seconds, like I do with the Ref button for QuantMT.  I'll have to look into that.

**Comment by dbgrande** [comment]
In my 2.8.0 release, Push has been updated so the triangle buttons now need a one-second long press to toggle.  Hopefully that's long enough to avoid accidental toggles, without being too annoying.

Thanks for the suggestion.

Just submitted to VCV Rack for update, but not sure how long the release process is these days.
