### ISSUE TITLE
Whishlist - M8 & S8 modules

### ISSUE THREAD

**Issue by firolightfog** [dbgrande/GrandeModular#2]
Would you please consider creating a simple '8-channel polyphonic merge' module? 

I know that there are 16-channel (VCV Merge) and 4-channel (your great MS4, Aria Salvatrice's Swerge & Werge) modules but no 8-channel ones. I also noticed that I regularly find myself putting a bunch of your MS4 everywhere and not using half of the module. A simple 3HP GrandeModular merge/split would so nice.

Best regards, Andras

**Comment by dbgrande** [comment]
Done. Merge8 and Split8 have been officially released to the VCV Rack 2 library.

Thanks for the suggestion.
