### ISSUE TITLE
Wishlist - CV2gate 

### ISSUE THREAD

**Issue by firolightfog** [dbgrande/GrandeModular#5]
Would you please consider a simple CV2gate module? 

<img width="292" alt="image" src="https://user-images.githubusercontent.com/34127628/169282231-b04d8416-00d3-4a3e-9d08-d5359e8d7185.png">

Best regards, Andras

**Comment by dbgrande** [comment]
Compare3 is now available in the VCV Rack Library.

Thanks for the suggestion.
