### ISSUE TITLE
Tails feature request

### ISSUE THREAD

**Issue by ContemporaryInsanity** [dbgrande/GrandeModular#6]
When Tails is bypassed could you pass inputs to outputs unmodified please.

**Comment by ContemporaryInsanity** [comment]
Also, when using Tails, I lose any pitch bends, so I'm assuming you're sampling v/oct on gate.  Could you pass v/oct as is to preserve pitch bends, or add an option to enable such?

**Comment by dbgrande** [comment]
Bypassing V/Oct and Gate inputs to outputs makes sense. Not sure why I didn't think of it before. However, if the builtin VCA is being used to modulate the corresponding envelope, bypassing this at the same time won't work right.

Yes, Tails samples V/Oct on the gate. I'm not sure how I could get it to preserve pitch bends.

**Comment by ContemporaryInsanity** [comment]
"I'm not sure how I could get it to preserve pitch bends."

Just route v/oct input to current v/oct out poly channel instead of sample & set on gate, just switch channel on gate?

**Comment by ContemporaryInsanity** [comment]
& yeah, I meant v/oct & gate bypass, not all io.  I don't use the VCA bit.

**Comment by dbgrande** [comment]
All right. I created a test version of Tails with an option to **Don't latch current note,** in addition to the bypasses.

With the original design, the rising edge of Gate increments to the next note's channel and latches the current V/Oct value.

With this new option enabled, the rising edge of Gate increments to the next note's channel, which now becomes the point where the previous V/Oct value is latched to the previous note's channel.

Some observations with Marbles using X2 -> V/Oct and t2 -> Gate, which outputs both on the same cycle:
  - With the original design, if the V/Oct input is delayed one or more cycles relative to Gate, the previous V/Oct value is latched into the current note's channel. Adding sample delays to the Gate input lines things up again, and there's no problem if multiple delays are added.
  - With the new option enabled, if the Gate is delayed one or more cycles relative to V/Oct, this gives time for the new V/Oct value to be captured for the tail of the previous note. Extra sample delays need to be added to the V/Oct input to avoid this, and there doesn't seem to be a problem adding a few extra.

Would you be interested in a copy of this file to test out?

**Comment by ContemporaryInsanity** [comment]
If you can post a linux binary that'd be great.  My build system is broken atm and I'm not sure why & don't currently have time to sort it.

**Comment by dbgrande** [comment]
I'm exploring options to internally add delay to Tails to see if I can address the issues above, without causing new ones.

Then I'll see what it takes to post a binary—Linux is my primary system.

Won't be today, since I also have other things I need to do.

**Comment by dbgrande** [comment]
I updated the linux binary to a temporary repo:

https://github.com/dbgrande/TailsBeta (in the linux-release dir)

It's a new renamed plugin with just the new Tails module, so it can be loaded in parallel with my Grande plugin.

**Comment by ContemporaryInsanity** [comment]
[0.144 warn src/plugin.cpp:174 loadPlugin] Could not load plugin /home/ewen/.Rack2/plugins/TailsBeta: Failed to load library /home/ewen/.Rack2/plugins/TailsBeta/plugin.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.35' not found (required by /home/ewen/.Rack2/plugins/TailsBeta/plugin.so)

**Comment by dbgrande** [comment]
I added an Ubuntu-20.04 compiled version, in addition to the original Fedora-36 compiled version.

**Comment by ContemporaryInsanity** [comment]
Perfect so far!  Thank you :)

**Comment by dbgrande** [comment]
The updated Tails module is now available in the VCV library. No need for the Beta repository anymore.
